/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: germydan (https://sketchfab.com/germydan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-07c3674cfc26460d803f8f497f8c0f35
Title: Eye
*/

import type { ThreeElements } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import type * as THREE from 'three';

type GroupProps = ThreeElements['group'];

type GLTFResult = {
  nodes: {
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
  };
  materials: {
    wire_154154229: THREE.Material;
    '01___Default': THREE.Material;
  };
};

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF('/sample-models/eye.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-2.019, -0.244, -0.211]}>
        <group position={[-2.028, -2.028, -2.028]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.wire_154154229}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials['01___Default']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sample-models/eye.glb')

