/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Potted plant
*/

import type { ThreeElements } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import type * as THREE from 'three';

type GroupProps = ThreeElements['group'];

type GLTFResult = {
  nodes: {
    POT_WOOD_LEGS_WOODEN_LEGS_POT_0: THREE.Mesh;
    POTHOS_POTHOS_Mat_0: THREE.Mesh;
  };
  materials: {
    WOODEN_LEGS_POT: THREE.Material;
    POTHOS_Mat: THREE.Material;
  };
};

export function PottedPlantModel(props: GroupProps) {
  const { nodes, materials } = useGLTF('/sample-models/potted_plant.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POT_WOOD_LEGS_WOODEN_LEGS_POT_0.geometry}
          material={materials.WOODEN_LEGS_POT}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POTHOS_POTHOS_Mat_0.geometry}
          material={materials.POTHOS_Mat}
          position={[0.528, 48.985, 2.882]} //[0.528, 48.985, 2.882]
          scale={51.957}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/sample-models/potted_plant.glb');
