/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Elvis Thermo (https://sketchfab.com/elvis.thermo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robo-baby-head-bd09a0c8aa4f4f5fbc70612de0157aa2
Title: ROBO BABY HEAD
*/

import type { ThreeElements } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import type * as THREE from 'three';

type GroupProps = ThreeElements['group'];

type GLTFResult = {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_14: THREE.Mesh;
  };
  materials: {
    'Material.002': THREE.Material;
    'Material.004': THREE.Material;
    'Material.006': THREE.Material;
    'Material.008': THREE.Material;
  };
};

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF('/sample-models/robot_head.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.002']}
        rotation={[0, 0, -1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.006']}
        position={[0.825, 0, 0.261]}
        rotation={[-0.213, -0.279, 1.484]}
        scale={[0.101, 0.054, 0.101]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.004']}
        position={[0.922, -0.151, 0]}
        rotation={[0, 0, -1.885]}
        scale={0.153}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Material.008']}
        scale={0.923}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.002']}
        position={[0, -0.102, 0.969]}
        rotation={[Math.PI, 1.551, -1.563]}
        scale={[-0.406, 0.134, 0.405]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.008']}
        position={[0, -0.102, 0.969]}
        rotation={[Math.PI, 1.551, -1.563]}
        scale={[-0.406, 0.134, 0.405]}
      />
    </group>
  )
}

useGLTF.preload('/robot_head.glb')

