/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Window
*/

import type { ThreeElements } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import type * as THREE from 'three';

type GroupProps = ThreeElements['group'];

type GLTFResult = {
  nodes: {
    Rod_End_1_lambert1_0: THREE.Mesh;
    Rod_End_2_lambert1_0: THREE.Mesh;
    Rod_lambert1_0: THREE.Mesh;
    Ring_lambert1_0: THREE.Mesh;
    Ring1_lambert1_0: THREE.Mesh;
    Ring2_lambert1_0: THREE.Mesh;
    Ring3_lambert1_0: THREE.Mesh;
    Ring4_lambert1_0: THREE.Mesh;
    Ring5_lambert1_0: THREE.Mesh;
    Rod_Back_1_lambert1_0: THREE.Mesh;
    Rod_Back_2_lambert1_0: THREE.Mesh;
    Curtain_2_lambert1_0: THREE.Mesh;
    Curtain_1_lambert1_0: THREE.Mesh;
    Window_Frame2_lambert1_0: THREE.Mesh;
    Window_Frame3_lambert1_0: THREE.Mesh;
    Window_Frame4_lambert1_0: THREE.Mesh;
    Window_Frame5_lambert1_0: THREE.Mesh;
    Window_Frame6_lambert1_0: THREE.Mesh;
    Window_Frame7_lambert1_0: THREE.Mesh;
    Window_Frame8_lambert1_0: THREE.Mesh;
    Window_Frame9_lambert1_0: THREE.Mesh;
    Window_Frame10_lambert1_0: THREE.Mesh;
    Window_Frame11_lambert1_0: THREE.Mesh;
    Window_Frame1_lambert1_0: THREE.Mesh;
    Window_Frame_lambert1_0: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.Material;
  };
};

export function WindowModel(props: GroupProps) {
  const { nodes, materials } = useGLTF('/sample-models/window.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_End_1_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_End_2_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring1_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring2_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring3_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring4_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring5_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_Back_1_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_Back_2_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_2_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_1_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame2_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame3_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame4_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame5_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame6_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame7_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame8_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame9_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame10_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame11_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame1_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Frame_lambert1_0.geometry}
        material={materials.lambert1}
      />
    </group>
  );
}

useGLTF.preload('/sample-models/window.glb');
